# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designLabBox.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 629)
        MainWindow.setMaximumSize(QtCore.QSize(1098, 629))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.plotView = Plot2D(self.centralwidget)
        self.plotView.setMinimumSize(QtCore.QSize(700, 400))
        self.plotView.setMaximumSize(QtCore.QSize(700, 400))
        self.plotView.setObjectName("plotView")
        self.horizontalLayout_7.addWidget(self.plotView)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_4.setHorizontalSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout_6.addLayout(self.formLayout_4)
        self.adcDacLayout = QtWidgets.QGridLayout()
        self.adcDacLayout.setContentsMargins(-1, -1, 0, -1)
        self.adcDacLayout.setObjectName("adcDacLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.adcDacLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.adcDacLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_8.setContentsMargins(-1, 9, 146, -1)
        self.formLayout_8.setObjectName("formLayout_8")
        self.DACmaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.DACmaxLabel.setObjectName("DACmaxLabel")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.DACmaxLabel)
        self.dacLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dacLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dacLineEdit.setToolTip("")
        self.dacLineEdit.setMaxLength(4)
        self.dacLineEdit.setObjectName("dacLineEdit")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dacLineEdit)
        self.ADClineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ADClineEdit.setFont(font)
        self.ADClineEdit.setReadOnly(True)
        self.ADClineEdit.setObjectName("ADClineEdit")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ADClineEdit)
        self.ADClabel = QtWidgets.QLabel(self.centralwidget)
        self.ADClabel.setObjectName("ADClabel")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ADClabel)
        self.SetButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetButton.setEnabled(True)
        self.SetButton.setObjectName("SetButton")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.SetButton)
        self.adcDacLayout.addLayout(self.formLayout_8, 0, 1, 1, 2)
        self.verticalLayout_6.addLayout(self.adcDacLayout)
        self.modeLayout = QtWidgets.QHBoxLayout()
        self.modeLayout.setObjectName("modeLayout")
        self.signalFunctionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.signalFunctionBox.setObjectName("signalFunctionBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.signalFunctionBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sineRadioButton = QtWidgets.QRadioButton(self.signalFunctionBox)
        self.sineRadioButton.setChecked(True)
        self.sineRadioButton.setObjectName("sineRadioButton")
        self.horizontalLayout_6.addWidget(self.sineRadioButton)
        self.rampRadioButton = QtWidgets.QRadioButton(self.signalFunctionBox)
        self.rampRadioButton.setObjectName("rampRadioButton")
        self.horizontalLayout_6.addWidget(self.rampRadioButton)
        self.stepRadioButton = QtWidgets.QRadioButton(self.signalFunctionBox)
        self.stepRadioButton.setObjectName("stepRadioButton")
        self.horizontalLayout_6.addWidget(self.stepRadioButton)
        self.NoBiasRadioButton = QtWidgets.QRadioButton(self.signalFunctionBox)
        self.NoBiasRadioButton.setObjectName("NoBiasRadioButton")
        self.horizontalLayout_6.addWidget(self.NoBiasRadioButton)
        self.modeLayout.addWidget(self.signalFunctionBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.modeLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, -1, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.devicePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.devicePathLabel.setObjectName("devicePathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.devicePathLabel)
        self.devicePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.devicePathLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.devicePathLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.devicePathLineEdit.setObjectName("devicePathLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.devicePathLineEdit)
        self.deviceBaudrateLabel = QtWidgets.QLabel(self.centralwidget)
        self.deviceBaudrateLabel.setObjectName("deviceBaudrateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.deviceBaudrateLabel)
        self.deviceBaudrateLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.deviceBaudrateLineEdit.setEnabled(True)
        self.deviceBaudrateLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.deviceBaudrateLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.deviceBaudrateLineEdit.setObjectName("deviceBaudrateLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.deviceBaudrateLineEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(48, 0, 55, 1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ConnectButton.setIconSize(QtCore.QSize(16, 16))
        self.ConnectButton.setObjectName("ConnectButton")
        self.gridLayout.addWidget(self.ConnectButton, 0, 0, 1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.verticalLayout_5.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.devicePathLineEdit, self.deviceBaudrateLineEdit)
        MainWindow.setTabOrder(self.deviceBaudrateLineEdit, self.ConnectButton)
        MainWindow.setTabOrder(self.ConnectButton, self.sineRadioButton)
        MainWindow.setTabOrder(self.sineRadioButton, self.rampRadioButton)
        MainWindow.setTabOrder(self.rampRadioButton, self.stepRadioButton)
        MainWindow.setTabOrder(self.stepRadioButton, self.NoBiasRadioButton)
        MainWindow.setTabOrder(self.NoBiasRadioButton, self.plotView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LabBox"))
        self.DACmaxLabel.setText(_translate("MainWindow", "DACmax"))
        self.dacLineEdit.setStatusTip(_translate("MainWindow", "DAC value in mA, Range is 0 to 4059"))
        self.dacLineEdit.setText(_translate("MainWindow", "3549"))
        self.ADClineEdit.setText(_translate("MainWindow", "00"))
        self.ADClabel.setText(_translate("MainWindow", "ADC in (mv)"))
        self.SetButton.setText(_translate("MainWindow", "Set"))
        self.signalFunctionBox.setTitle(_translate("MainWindow", "Mode:"))
        self.sineRadioButton.setText(_translate("MainWindow", "Sine"))
        self.rampRadioButton.setText(_translate("MainWindow", "Ramp"))
        self.stepRadioButton.setText(_translate("MainWindow", "Step"))
        self.NoBiasRadioButton.setText(_translate("MainWindow", "No Bias"))
        self.devicePathLabel.setText(_translate("MainWindow", "Device path:"))
        self.devicePathLineEdit.setStatusTip(_translate("MainWindow", "To find device seral port use\"dmesg | grep tty\" in CMD"))
        self.devicePathLineEdit.setText(_translate("MainWindow", "/dev/ttyACM0"))
        self.deviceBaudrateLabel.setText(_translate("MainWindow", "Baudrate:"))
        self.deviceBaudrateLineEdit.setStatusTip(_translate("MainWindow", "device baude rate "))
        self.deviceBaudrateLineEdit.setText(_translate("MainWindow", "115200"))
        self.ConnectButton.setStatusTip(_translate("MainWindow", "Start communicating with device."))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))

from plot2d import Plot2D
